var cookieName = "testCookie",
    loginForm = "login-form",
    loginFormName = "name",
    loginFormPassword = "password",
    popup = "popup__overlay",
    popupHidden = " popup__overlay_hidden",
    popupActive = " popup__overlay_active",
    dashboard = "dashboard",
    dashboardHidden = " b-dashboard_hidden",
    dashboardActive = " b-dashboard_active",
    dashboardGreating = "dashboard-greating",
    greating = "Hello ",
    submitButton = "submit-button",
    logOutButton = "log-out-button",
    infoTime  = 'js-info__time-value',
    infoTimeNotation = "js-info__time-notation",
    timeAM = "AM",
    timePM = "PM",
    action = 'click',
    infoDay = "js-info__day",
    forecastToday = "js-forecast_today",
    forecastYesterday = "js-forecast_yesterday",
    forecastTomorrow = "js-forecast_tomorrow",
    api = "http://api.openweathermap.org/data/2.5/weather?q=",
    apiOther = ",ua&units=metric&APPID=b04a06714afca79362dec1420563b1e7",
    cityTest = "Kiev",
    weatherStatus = "status",
    weatherTemp = "temp";